
spring:
  datasource:
    url:  jdbc:mysql://47.97.214.211:3306/mislab?useSSL=false&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: AaAa123!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.lgl.zhuye.pojo
server:
  port: 8081

img:
  path: C:/img/